name: Deploy to Firebase Hosting on PR
'on':
  pull_request:
    branches:
      - main
permissions:
  checks: write
jobs:
  build_and_preview:
    if: '${{ github.event_name == ''pull_request'' }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.CHAVE_FIREBASE }}'
          projectId: '${{ secrets.ID_PROJETO }}'
          tag: 'v1.2.3'  # Adicione o nome da versão aqui



